# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

anchor_1: &defaults
  working_directory: /tmp/reibo
  docker:
    - image: circleci/node:10.9.0-stretch-browsers


jobs:
  install:
    <<: *defaults

    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              sudo npm install -g npm@$NPM_VERSION
              npm ci
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - restore_cache:
          name: Restore build
          key: build-{{ .Revision }}
      - run:
          name: Create the build
          command: npm run build
      - save_cache:
          name: Save build
          key: build-{{ .Revision }}
          paths:
            - dist/

  prod-publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore build
          key: build-{{ .Revision }}
      - run: git config user.name "Bo Vandersteene"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: pre-publish
          command: cp README.md dist/  && cp package.json dist/
      - run:
          name: publish
          command: npm publish --access=public --registry=https://registry.npmjs.org/ --folder dist
      #
      # - run: npm run lib:publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - prod-publish:
          requires:
            - build
          filters:
            branches:
              only: master
